// Map of reliable Wikimedia Commons image URLs that allow direct embedding
const wixImageUrls = {
  // Common herbs
  'yarrow': 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Achillea_millefolium_illustration.jpg',
  'anise hyssop': 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Agastache_foeniculum_Anise_Hyssop_1.jpg',
  'milkweed': 'https://upload.wikimedia.org/wikipedia/commons/9/93/Asclepias_syriaca.jpg',
  'echinacea': 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Echinacea_purpurea_003.JPG',
  'sage': 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Sage_leaves.jpg',
  'blue sage': 'https://upload.wikimedia.org/wikipedia/commons/2/20/Salvia_azurea.jpg',
  'rosemary': 'https://upload.wikimedia.org/wikipedia/commons/8/83/Rosemary_in_bloom.jpg',
  'thyme': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Thymus_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-274.jpg/800px-Thymus_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-274.jpg',
  'mint': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Mentha_x_piperita_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-101.jpg/800px-Mentha_x_piperita_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-101.jpg',
  'mountain mint': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Pycnanthemum_tenuifolium.jpg',
  'oregano': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Origanum_vulgare_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-207.jpg',
  'basil': 'https://upload.wikimedia.org/wikipedia/commons/9/90/Basil-Basilico-Ocimum_basilicum-albahaca.jpg',
  'parsley': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Petroselinum_crispum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-231.jpg/800px-Petroselinum_crispum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-231.jpg',
  'cilantro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/A_scene_of_Coriander_leaves.JPG/1024px-A_scene_of_Coriander_leaves.JPG',
  'dill': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Anethum_graveolens_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-12.jpg/724px-Anethum_graveolens_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-12.jpg',
  'chamomile': 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Kamille_Matricaria_chamomilla.jpg',
  'chives': 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Allium_schoenoprasum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-10.jpg',
  'marjoram': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Illustration_Origanum_majorana0.jpg',
  
  // Vegetables
  'tomato': 'https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg',
  'pepper': 'https://upload.wikimedia.org/wikipedia/commons/7/74/Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg',
  'bell pepper': 'https://upload.wikimedia.org/wikipedia/commons/6/60/Capsicum_annuum_fruits_IMGP0044.jpg',
  'broccoli': 'https://upload.wikimedia.org/wikipedia/commons/0/03/Broccoli_and_cross_section_edit.jpg',
  'kale': 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Boerenkool.jpg',
  'cabbage': 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Cabbage_in_a_stack.jpg',
  'beets': 'https://upload.wikimedia.org/wikipedia/commons/2/25/Beetroot_jm26647.jpg',
  'spinach': 'https://upload.wikimedia.org/wikipedia/commons/3/37/Spinacia_oleracea_Spinach_vegetable_green_leaves_eaten_raw_cooked_plant_1.jpg',
  'collards': 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Collard-Greens-Bundle.jpg',
  'pac choi': 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Pak_choi.jpg',
  'lettuce': 'https://upload.wikimedia.org/wikipedia/commons/d/da/Iceberg_lettuce_in_SB.jpg',
  'broccolini': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Brocccolini_Tanigawa_Kamo.jpg',
  'jalapeno': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Jalape%C3%B1o_cross_section.jpg',
  'banana pepper': 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Yellow_bell_peppers.jpg',
  
  // Flowers & Native Plants
  'mistflower': 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Conoclinium_coelestinum.jpg',
  'joe pye weed': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Eutrochium_purpureum_-_Purple_Joe-Pye_weed.jpg',
  'little blue stem': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Schizachyrium_scoparium_Little_Bluestem_2zz.jpg',
  'catnip': 'https://upload.wikimedia.org/wikipedia/commons/8/85/Catnip_flowers.jpg',
  'passionflower': 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Passiflora_incarnata_flower.jpg',
  'royal catchfly': 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Silene_regia_%28royal_catchfly%29.jpg',
  'blue vervain': 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Verbena_hastata.jpg',
  'coneflower': 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Echinacea_purpurea_%27Fatal_Attraction%27.jpg',
  'black eyed susan': 'https://upload.wikimedia.org/wikipedia/commons/2/29/Rudbeckia_Black-eyed-Susan.jpg',
  'brown eyed susan': 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Rudbeckia_triloba_%28Brown-eyed_Susan%29.jpg',
  'indigo': 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Baptisia_australis_2.jpg',
  'blue indigo': 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Baptisia_australis_2.jpg',
  'wild indigo': 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Baptisia_alba.jpg',
  'river oats': 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Chasmanthium_latifolium_Inland_Sea_Oats_600.jpg',
  'silene': 'https://upload.wikimedia.org/wikipedia/commons/2/25/Silene_dioica_%2820150604%29_close_up_female.jpg',
  'aster': 'https://upload.wikimedia.org/wikipedia/commons/2/20/Aster_amellus.jpg',
  'boneset': 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Eupatorium_perfoliatum_Boneset_5952.jpg',
  'rattlesnake master': 'https://upload.wikimedia.org/wikipedia/commons/3/38/Rattlesnake_master_bloom.jpg',
  'swamp marigold': 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Bidens_cernua.jpg',
  'lance leaf coreopsis': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Coreopsis_lanceolata.jpg',
  'coreopsis': 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Coreopsis_tinctoria_Flowers.jpg',
  'lespedeza': 'https://upload.wikimedia.org/wikipedia/commons/3/37/Lespedeza_capitata.jpg',
  'cardinal flower': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Lobelia_cardinalis.jpg',
  'monarda': 'https://upload.wikimedia.org/wikipedia/commons/4/48/Monarda_didyma_-_Oswego_Tea_-_Beebalm_2.jpg',
  'bee balm': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Monarda_punctata_flowers.jpg',
  'hibiscus': 'https://upload.wikimedia.org/wikipedia/commons/9/99/Hibiscus_rosa-sinensis_flower_2.jpg',
  'rose mallow': 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Hibiscus_moscheutos_Rose_Mallow_Pink_1.jpg',
  'nasturtium': 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Tropaeolum_majus.jpg',
  'blue salvia': 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Salvia_azurea_GotBot_2015_002.jpg',
  'pink salvia': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Salvia_horminum_Pink_Sunday_1.jpg',
  'skullcap': 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Scutellaria_lateriflora_001.jpg',
  'ironweed': 'https://upload.wikimedia.org/wikipedia/commons/7/71/Vernonia_gigantea.jpg',
  'st. johns wort': 'https://upload.wikimedia.org/wikipedia/commons/9/95/St_Johns_wort_flowers.jpg',
  'woodmint': 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Blephilia_ciliata.jpg',
  'pycnanthemum': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Pycnanthemum_virginianum.jpg',
  'grey headed coneflower': 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Ratibida_pinnata.jpg',
  'elecampane': 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Elecampane_-_Inula_helenium.jpg',
  'valerian': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Valeriana_officinalis_jfg.jpg',
  'nettle': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Brennnessel_1.jpg',
  'borage': 'https://upload.wikimedia.org/wikipedia/commons/1/19/Starflower_Borage_%28Borago_officinalis%29_%284825703593%29.jpg',
  'calendula': 'https://upload.wikimedia.org/wikipedia/commons/7/79/Calendula_officinalisRHu.JPG',
  'sunflower': 'https://upload.wikimedia.org/wikipedia/commons/4/40/Sunflower_sky_backdrop.jpg',
  'clover': 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Red_Clover_%28Trifolium_pratense%29_flowers%2C_Baltasound_-_geograph.org.uk_-_1418456.jpg',
  'cutleaf coneflower': 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Rudbeckia_laciniata.jpg',
  
  // Milkweed specific variants
  'milkweed, poke': 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Asclepias_exaltata_2.jpg',
  'milkweed, rose': 'https://upload.wikimedia.org/wikipedia/commons/4/43/Asclepias_incarnata.jpg',
  'milkweed, butterfly': 'https://upload.wikimedia.org/wikipedia/commons/7/71/Asclepias_tuberosa.jpg',
  'milkweed, whorled': 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Asclepias_verticillata.jpg',
  
  // Joe Pye Weed specific variants
  'joe pye weed, little': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Eutrochium_purpureum_-_Purple_Joe-Pye_weed.jpg',
  'joe pye weed, hollow': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Eutrochium_purpureum_-_Purple_Joe-Pye_weed.jpg',
  'joe pye weed, sweet': 'https://upload.wikimedia.org/wikipedia/commons/b/be/Eutrochium_purpureum_-_Purple_Joe-Pye_weed.jpg',
  
  // Sunflower specific variants
  'sunflower, woodland': 'https://upload.wikimedia.org/wikipedia/commons/5/59/Helianthus_divaricatus_UMFS_2.jpg',
  'sunflower, western': 'https://upload.wikimedia.org/wikipedia/commons/4/40/Sunflower_sky_backdrop.jpg',
  
  // Category fallbacks - reliable general images
  'medicinal-herbs': 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Echinacea_purpurea_003.JPG',
  'culinary-herbs': 'https://upload.wikimedia.org/wikipedia/commons/9/90/Basil-Basilico-Ocimum_basilicum-albahaca.jpg', 
  'pollinator-friendly': 'https://upload.wikimedia.org/wikipedia/commons/2/29/Rudbeckia_Black-eyed-Susan.jpg',
  'native-plants': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Schizachyrium_scoparium_Little_Bluestem_2zz.jpg',
};

module.exports = wixImageUrls; 